import { Knex } from 'knex';
import { ETableNames } from '../ETableNames';


export const seed = async (knex: Knex) => {

  const [{ count }] = await knex(ETableNames.marca).count<[{ count: number }]>('* as count');
  if (!Number.isInteger(count) || Number(count) > 0) return;

  const marcasToInsert = carBrands.map(nomeMarca => ({ nome: nomeMarca }));
  await knex(ETableNames.marca).insert(marcasToInsert);

};


const carBrands: string[] = [
    "Toyota",
    "Volkswagen",
    "Ford",
    "Honda",
    "Chevrolet",
    "Nissan",
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Hyundai",
    "Kia",
    "Renault",
    "Peugeot",
    "Fiat",
    "Mazda",
    "Subaru",
    "Mitsubishi",
    "Lexus",
    "Land Rover",
    "Jaguar",
    "Volvo",
    "Porsche",
    "Jeep",
    "Dodge",
    "Ram",
    "Chrysler",
    "Buick",
    "Cadillac",
    "GMC",
    "Acura",
    "Infiniti",
    "Lincoln",
    "Tesla",
    "Ferrari",
    "Lamborghini",
    "Maserati",
    "Bentley",
    "Rolls-Royce",
    "Aston Martin",
    "Alfa Romeo",
    "Bugatti",
    "Genesis",
    "Mini",
    "Suzuki",
    "Saab",
    "Citroën",
    "SEAT",
    "Skoda",
    "Opel",
    "Holden",
    "Isuzu",
    "Daihatsu",
    "McLaren",
    "Pagani",
    "Koenigsegg",
    "Hummer",
    "Pontiac",
    "Saturn",
    "Oldsmobile",
    "Fisker",
    "Rivian",
    "Lucid",
    "Polestar",
    "Smart",
    "Scion",
    "MG",
    "Rover",
    "Lada",
    "Tata",
    "Mahindra",
    "Great Wall",
    "Geely",
    "BYD",
    "Chery",
    "BAIC",
    "FAW",
    "Dongfeng",
    "Zotye",
    "Haval",
    "Proton",
    "Perodua",
    "SsangYong",
    "Daewoo",
    "Maruti Suzuki",
    "Datsun",
    "Plymouth",
    "Studebaker",
    "Packard",
    "DeLorean",
    "Spyker",
    "Wiesmann",
    "Mosler",
    "Saleen",
    "Vector",
    "Noble",
    "TVR",
    "Gumpert",
    "Caterham",
    "Morgan",
    "Zenvo",
    "Faraday Future"
];


/*
const carModels: { [brand: string]: string[] } = {
    "Toyota": ["Camry", "Corolla", "RAV4", "Highlander", "Tacoma", "Tundra", "Prius", "Avalon", "Supra", "4Runner"],
    "Volkswagen": ["Golf", "Jetta", "Passat", "Tiguan", "Atlas", "Beetle", "Polo", "Touareg", "Arteon", "ID.4"],
    "Ford": ["F-150", "Mustang", "Escape", "Explorer", "Edge", "Bronco", "Ranger", "Expedition", "Fusion", "EcoSport"],
    "Honda": ["Civic", "Accord", "CR-V", "Pilot", "Fit", "Odyssey", "Ridgeline", "HR-V", "Insight", "Passport"],
    "Chevrolet": ["Silverado", "Equinox", "Malibu", "Traverse", "Tahoe", "Colorado", "Camaro", "Impala", "Suburban", "Trax"],
    "Nissan": ["Altima", "Sentra", "Rogue", "Pathfinder", "Murano", "Frontier", "Maxima", "Versa", "Titan", "370Z"],
    "BMW": ["3 Series", "5 Series", "X5", "X3", "7 Series", "X1", "4 Series", "2 Series", "M3", "i3"],
    "Mercedes-Benz": ["C-Class", "E-Class", "S-Class", "GLC", "GLE", "GLA", "CLS", "G-Class", "A-Class", "SL"],
    "Audi": ["A3", "A4", "A6", "Q5", "Q7", "Q3", "A8", "Q8", "RS7", "TT"],
    "Hyundai": ["Elantra", "Sonata", "Tucson", "Santa Fe", "Palisade", "Kona", "Accent", "Veloster", "Ioniq", "Venue"],
    "Kia": ["Soul", "Sportage", "Sorento", "Optima", "Forte", "Stinger", "Telluride", "Seltos", "Niro", "Rio"],
    "Renault": ["Clio", "Megane", "Captur", "Kadjar", "Zoe", "Koleos", "Twingo", "Scenic", "Espace", "Kangoo"],
    "Peugeot": ["208", "308", "3008", "508", "2008", "5008", "Rifter", "Traveller", "Expert", "Boxer"],
    "Fiat": ["500", "Panda", "Tipo", "Punto", "Ducato", "Doblo", "Uno", "Mobi", "Toro", "Cronos"],
    "Mazda": ["Mazda3", "Mazda6", "CX-5", "CX-9", "MX-5", "CX-3", "CX-30", "Mazda2", "BT-50", "RX-8"],
    "Subaru": ["Impreza", "Outback", "Forester", "Legacy", "Crosstrek", "WRX", "BRZ", "Ascent", "XV", "Levorg"],
    "Mitsubishi": ["Outlander", "Pajero", "Lancer", "ASX", "Mirage", "Eclipse Cross", "Triton", "Galant", "Attrage", "Xpander"],
    "Lexus": ["RX", "ES", "NX", "GX", "LS", "IS", "UX", "LX", "LC", "RC"],
    "Land Rover": ["Range Rover", "Discovery", "Defender", "Evoque", "Sport", "Velar", "Freelander", "Series III", "Discovery Sport", "P400e"],
    "Jaguar": ["F-Pace", "XE", "XF", "XJ", "F-Type", "E-Pace", "I-Pace", "XK", "XKR", "XJ220"],
    "Volvo": ["XC90", "XC60", "XC40", "S60", "S90", "V60", "V90", "C40", "V40", "850"],
    "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Taycan", "Boxster", "Cayman", "918 Spyder", "Carrera GT", "924"],
    "Jeep": ["Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Renegade", "Gladiator", "Patriot", "Liberty", "Commander", "Wagoneer"],
    "Dodge": ["Charger", "Challenger", "Durango", "Journey", "Grand Caravan", "Viper", "Dart", "Magnum", "Neon", "Caliber"],
    "Ram": ["1500", "2500", "3500", "Dakota", "ProMaster", "Chassis Cab", "ProMaster City", "Rebel", "TRX", "Big Horn"],
    "Chrysler": ["300", "Pacifica", "Voyager", "Aspen", "Sebring", "Town & Country", "Crossfire", "PT Cruiser", "Concorde", "New Yorker"],
    "Buick": ["Enclave", "Encore", "Envision", "Regal", "Lacrosse", "Verano", "Cascada", "Lucerne", "Park Avenue", "Rainier"],
    "Cadillac": ["Escalade", "XT5", "XT4", "XT6", "CT5", "CT4", "CT6", "ATS", "XTS", "CTS"],
    "GMC": ["Sierra", "Canyon", "Yukon", "Acadia", "Terrain", "Savanna", "Jimmy", "Envoy", "Sonoma", "Typhoon"],
    "Acura": ["MDX", "RDX", "TLX", "ILX", "NSX", "RLX", "TSX", "ZDX", "TL", "RSX"],
    "Infiniti": ["Q50", "QX60", "QX80", "QX50", "QX70", "Q60", "QX30", "Q70", "G37", "FX35"],
    "Lincoln": ["Navigator", "Aviator", "Corsair", "Nautilus", "MKZ", "MKX", "Continental", "MKT", "MKC", "Town Car"],
    "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Roadster", "Cybertruck", "Semi", "Model 2", "Model P", "Model Q"],
    "Ferrari": ["488", "812 Superfast", "SF90 Stradale", "F8 Tributo", "Portofino", "Roma", "LaFerrari", "California", "GTC4Lusso", "458 Italia"],
    "Lamborghini": ["Huracan", "Aventador", "Urus", "Gallardo", "Murcielago", "Diablo", "Countach", "Sian", "Reventon", "Veneno"],
    "Maserati": ["Ghibli", "Quattroporte", "Levante", "GranTurismo", "MC20", "GranCabrio", "Kubang", "Alfieri", "3200 GT", "Bora"],
    "Bentley": ["Bentayga", "Continental GT", "Flying Spur", "Mulsanne", "Arnage", "Brooklands", "Azure", "Turbo R", "Corniche", "Blower"],
    "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Silver Shadow", "Silver Spirit", "Silver Wraith", "Corniche", "Sweptail"],
    "Aston Martin": ["DB11", "Vantage", "DBX", "Rapide", "Vanquish", "DB9", "One-77", "DBS", "Vulcan", "Lagonda"],
    "Alfa Romeo": ["Giulia", "Stelvio", "4C", "8C", "GTV", "Spider", "147", "156", "Brera", "MiTo"],
    "Bugatti": ["Chiron", "Veyron", "Divo", "Centodieci", "Bolide", "La Voiture Noire", "EB110", "Type 35", "Type 57", "Type 41 Royale"],
    "Genesis": ["G70", "G80", "G90", "GV70", "GV80", "G70 Shooting Brake", "Essentia", "Mint", "X Concept", "New York Concept"],
    "Mini": ["Cooper", "Clubman", "Countryman", "Paceman", "Cabrio", "Roadster", "Coupe", "E", "John Cooper Works", "Electric"],
    "Suzuki": ["Swift", "Vitara", "Jimny", "Baleno", "Celerio", "Alto", "S-Cross", "Ignis", "Kizashi", "Grand Vitara"],
    "Saab": ["9-3", "9-5", "900", "9000", "9-4X", "9-7X", "Sonett", "96", "99", "Aero X"],
    "Citroën": ["C3", "C4", "C5 Aircross", "C1", "Berlingo", "C3 Aircross", "C4 Cactus", "C-Elysee", "DS3", "Ami"],
    "SEAT": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Toledo", "Alhambra", "Mii", "Cordoba", "Altea"],
    "Skoda": ["Octavia", "Superb", "Kodiaq", "Karoq", "Fabia", "Scala", "Kamiq", "Rapid", "Yeti", "Citigo"],
    "Opel": ["Corsa", "Astra", "Insignia", "Mokka", "Grandland X", "Crossland X", "Zafira", "Adam", "Karl", "Combo"],
    "Holden": ["Commodore", "Cruze", "Captiva", "Trax", "Colorado", "Barina", "Astra", "Malibu", "Spark", "Ute"],
    "Isuzu": ["D-Max", "MU-X", "Trooper", "Rodeo", "Ascender", "Hombre", "Amigo", "Axiom", "VehiCROSS", "Panther"],
    "Daihatsu": ["Terios", "Sirion", "Mira", "Copen", "Charade", "Rocky", "Hijet", "Tanto", "Move", "Altis"],
    "McLaren": ["720S", "P1", "570S", "600LT", "675LT", "MP4-12C", "650S", "GT", "Speedtail", "Artura"],
    "Pagani": ["Zonda", "Huayra", "C10", "Imola", "Zonda R", "Huayra BC", "Huayra Roadster", "Zonda Cinque", "Zonda F", "Zonda HP Barchetta"],
    "Koenigsegg": ["Agera", "Regera", "Jesko", "Gemera", "One:1", "CCX", "CCR", "Trevita", "CC8S", "Agera RS"],
    "Hummer": ["H1", "H2", "H3", "H3T", "EV", "Alpha", "H3X", "O2", "HX", "H1 Alpha"],
    "Pontiac": ["G6", "G8", "Solstice", "Firebird", "Trans Am", "Bonneville", "Grand Am", "GTO", "Vibe", "Sunfire"],
    "Saturn": ["Vue", "Ion", "Sky", "Aura", "Outlook", "Astra", "L-Series", "Relay", "S-Series", "SC"],
    "Oldsmobile": ["Alero", "Cutlass", "88", "98", "Achieva", "Aurora", "Intrigue", "Silhouette", "Bravada", "Firenza"],
    "Fisker": ["Karma", "Ocean", "EMotion", "Alaska", "Surf", "Latigo", "Sunset", "Viggo", "Tramonto", "Force 1"],
    "Rivian": ["R1T", "R1S", "A1T", "A1C", "R2T", "R2S", "RS1", "RS2", "RT1", "RT2"],
    "Lucid": ["Air", "Gravity", "Sapphire", "Pure", "Touring", "Dream Edition", "Grand Touring", "Grand Touring Performance", "Stealth", "Vision"],
    "Polestar": ["1", "2", "3", "4", "5", "6", "Precept", "O2", "1 Prototype", "2 Performance"],
    "Smart": ["Fortwo", "Forfour", "EQ Fortwo", "EQ Forfour", "Crossblade", "Roadster", "Coupé", "Cabrio", "ED", "K"],
    "Scion": ["tC", "xB", "xD", "iQ", "FR-S", "xA", "iM", "iA", "Hako Coupe", "C-HR"],
    "MG": ["MG3", "ZS", "HS", "GS", "6", "5", "3 SW", "ZR", "TF", "RV8"],
    "Rover": ["75", "45", "25", "200", "400", "600", "800", "Streetwise", "Maestro", "Montego"],
    "Lada": ["Niva", "Granta", "Vesta", "Xray", "Kalina", "Largus", "Samara", "Priora", "2107", "2105"],
    "Tata": ["Nano", "Tiago", "Tigor", "Harrier", "Safari", "Hexa", "Nexon", "Altroz", "Indica", "Aria"],
    "Mahindra": ["Thar", "Scorpio", "Bolero", "XUV500", "XUV300", "Marazzo", "KUV100", "TUV300", "Alturas G4", "Verito"],
    "Great Wall": ["Steed", "Wingle", "Haval H6", "Haval H9", "Haval M4", "Voleex C30", "Coolbear", "Florid", "Peri", "Haval F7"],
    "Geely": ["Emgrand", "Boyue", "Panda", "Binrui", "Xingyue", "Icon", "Borui", "Haoyue", "Vision", "GX3"],
    "BYD": ["Tang", "Song", "Han", "Qin", "Yuan", "F3", "e6", "Dolphin", "Seal", "T3"],
    "Chery": ["Tiggo", "Arrizo", "QQ", "Fulwin", "A1", "A3", "E5", "E3", "Tiggo 8", "Tiggo 7"],
    "BAIC": ["Senova X25", "Senova X35", "Senova X55", "BJ20", "BJ40", "BJ80", "EC5", "EU5", "EX3", "M60"],
    "FAW": ["Besturn X40", "Besturn X80", "Besturn B30", "Besturn B50", "Besturn T77", "Besturn T99", "Junpai D60", "Junpai A50", "Hongqi H5", "Hongqi H9"],
    "Dongfeng": ["S30", "H30", "AX7", "AX4", "AX3", "E30", "E70", "Joyear X3", "Joyear X5", "Joyear X6"],
    "Zotye": ["T600", "T700", "T800", "Z300", "Z500", "SR7", "SR9", "E200", "Damai X5", "Damai X7"],
    "Haval": ["H6", "H9", "H2", "H4", "F5", "F7", "M6", "M4", "H8", "H5"],
    "Proton": ["Saga", "Persona", "X70", "Iriz", "X50", "Preve", "Suprima S", "Waja", "Gen-2", "Satria Neo"],
    "Perodua": ["Myvi", "Axia", "Bezza", "Alza", "Aruz", "Kancil", "Kelisa", "Viva", "Rusa", "Nautica"],
    "SsangYong": ["Korando", "Tivoli", "Rexton", "Musso", "Actyon", "Kyron", "Rodius", "XLV", "Stavic", "Korando Sports"],
    "Daewoo": ["Lanos", "Nubira", "Leganza", "Matiz", "Kalos", "Tacuma", "Evanda", "Lacetti", "Magnus", "Prince"],
    "Maruti Suzuki": ["Alto", "Swift", "Baleno", "Vitara Brezza", "Dzire", "Celerio", "Ertiga", "Wagon R", "Ignis", "S-Presso"],
    "Datsun": ["GO", "GO+", "Redi-GO", "Mi-DO", "on-DO", "240Z", "280ZX", "510", "Bluebird", "Fairlady"],
    "Plymouth": ["Voyager", "Prowler", "Barracuda", "Fury", "Valiant", "Satellite", "Superbird", "Belvedere", "Road Runner", "Acclaim"],
    "Studebaker": ["Commander", "Champion", "Avanti", "Hawk", "Lark", "President", "Silver Hawk", "Golden Hawk", "Speedster", "Wagonaire"],
    "Packard": ["Packard Eight", "Packard Twelve", "Clipper", "Caribbean", "Patrician", "Mayfair", "Panther", "Hawk", "Executive", "Custom Eight"],
    "DeLorean": ["DMC-12", "Alpha5", "DMC-24", "DMC-80", "DMC-21", "DMC-44", "DMC-55", "DMC-80/EX", "DMC-24/EX", "DMC-20"],
    "Spyker": ["C8", "C8 Laviolette", "C8 Aileron", "C12 Zagato", "C8 Preliator", "C8 Double 12", "D12 Peking-to-Paris", "C8 Spyder", "C8 Spyder GT2R", "C8 Laviolette GT2R"],
    "Wiesmann": ["MF3", "MF4", "MF5", "GT", "Roadster", "Spyder", "GT MF4-CS", "GT MF5-V10", "GT MF4-S", "GT MF4-R"],
    "Mosler": ["MT900", "MT900S", "Consulier GTP", "Raptor GTR", "Intruder", "J-10", "TwinStar", "Photon", "RH90", "Raptor"],
    "Saleen": ["S7", "S1", "Mustang", "S302", "S331", "S5S Raptor", "SA-10", "SR", "SSC", "XP8"],
    "Vector": ["W8", "M12", "WX-3", "SRV8", "Avtech WX-8", "W2", "SC", "WX-3R", "SC/25", "M12 LM"],
    "Noble": ["M12", "M400", "M600", "M10", "M14", "M15", "M600 Speedster", "M600 CarbonSport", "M600 SVR", "M600 SVS"],
    "TVR": ["Griffith", "Tuscan", "Chimaera", "Sagaris", "Cigarette", "Ceratopia", "Tamora", "T350", "Cerbera", "Vixen"],
    "Gumpert": ["Apollo", "Apollo Sport", "Apollo Enraged", "Apollo N", "Tornante", "Explosion", "Apollo S", "Apollo IE", "Apollo Arrow", "Apollo Intensa Emozione"],
    "Caterham": ["Seven 160", "Seven 275", "Seven 485", "Seven 620", "Super Seven 1600", "Seven 310", "Seven 360", "Seven 420", "Seven 620R", "Seven 420R"],
    "Morgan": ["Plus 4", "4/4", "Roadster", "Aero 8", "3-Wheeler", "Plus 8", "EV3", "Plus 6", "Plus 8 GTR", "Super 3"],
    "Zenvo": ["ST1", "TS1 GT", "TSR-S", "TSR", "TS1", "ST1-50", "TSR-GT", "TS1-LE", "TSR-P", "TS1-R"],
    "Faraday Future": ["FF 91", "FF 81", "FF 71", "FF V9", "FF V7", "FF V5", "FFX1", "FFX2", "FF91-F", "FF81-F"]
};

*/
